/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DCCMS;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame {
 
 
        
    /**
     * Creates new form Home
     */
    public Home() {
        
        initComponents();
         
        setColor(btn_1); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_3,btn_4}, new JPanel[]{ind_3, ind_4});
        show_result_pane.setVisible(false);
        uid.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        side_pane = new javax.swing.JPanel();
        btn_1 = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_3 = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_4 = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        title_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        show_result_pane = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        mild_reslt = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        wloss_reslt = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        maintain_reslt = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        calci_panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        text_age = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        text_height = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        text_weight = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        activity_combobox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        weight_loss_btn = new javax.swing.JButton();
        weight_gain_btn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        profile_icon = new javax.swing.JLabel();
        profile_name = new javax.swing.JLabel();
        logout_btn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane.setBackground(new java.awt.Color(23, 35, 51));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_1.setBackground(new java.awt.Color(23, 35, 51));
        btn_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_1MousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Home");

        javax.swing.GroupLayout btn_1Layout = new javax.swing.GroupLayout(btn_1);
        btn_1.setLayout(btn_1Layout);
        btn_1Layout.setHorizontalGroup(
            btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_1Layout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(0, 66, Short.MAX_VALUE))
        );
        btn_1Layout.setVerticalGroup(
            btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_1Layout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 120, -1));

        btn_3.setBackground(new java.awt.Color(23, 35, 51));
        btn_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_3MousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Set Goal");

        javax.swing.GroupLayout btn_3Layout = new javax.swing.GroupLayout(btn_3);
        btn_3.setLayout(btn_3Layout);
        btn_3Layout.setHorizontalGroup(
            btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_3Layout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(0, 56, Short.MAX_VALUE))
        );
        btn_3Layout.setVerticalGroup(
            btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_3Layout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 120, -1));

        btn_4.setBackground(new java.awt.Color(23, 35, 51));
        btn_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_4MousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Track Calories");

        javax.swing.GroupLayout btn_4Layout = new javax.swing.GroupLayout(btn_4);
        btn_4.setLayout(btn_4Layout);
        btn_4Layout.setHorizontalGroup(
            btn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_4Layout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        btn_4Layout.setVerticalGroup(
            btn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_4Layout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 120, -1));

        getContentPane().add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 590));

        title_panel.setBackground(new java.awt.Color(71, 120, 197));
        title_panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                title_panelMouseDragged(evt);
            }
        });
        title_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                title_panelMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana Pro Cond Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(176, 221, 243));
        jLabel1.setText("Daily Calorie Calculator and Management System");

        uid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout title_panelLayout = new javax.swing.GroupLayout(title_panel);
        title_panel.setLayout(title_panelLayout);
        title_panelLayout.setHorizontalGroup(
            title_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, title_panelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(uid, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(177, 177, 177))
        );
        title_panelLayout.setVerticalGroup(
            title_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(title_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(title_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 950, 50));

        jPanel6.setBackground(new java.awt.Color(84, 127, 206));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        show_result_pane.setBackground(new java.awt.Color(84, 127, 206));

        jLabel13.setFont(new java.awt.Font("Caviar Dreams", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Mild Weight Loss ");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        mild_reslt.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        mild_reslt.setForeground(new java.awt.Color(255, 255, 255));
        mild_reslt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mild_reslt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel15.setFont(new java.awt.Font("Caviar Dreams", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Maintain Weight");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        wloss_reslt.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        wloss_reslt.setForeground(new java.awt.Color(255, 255, 255));
        wloss_reslt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wloss_reslt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel17.setFont(new java.awt.Font("Caviar Dreams", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Weight Loss ");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel7.setText("(0.5 kg / Week)");

        jLabel9.setText("(0.25 kg / Week)");

        maintain_reslt.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        maintain_reslt.setForeground(new java.awt.Color(255, 255, 255));
        maintain_reslt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maintain_reslt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout show_result_paneLayout = new javax.swing.GroupLayout(show_result_pane);
        show_result_pane.setLayout(show_result_paneLayout);
        show_result_paneLayout.setHorizontalGroup(
            show_result_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(show_result_paneLayout.createSequentialGroup()
                .addGroup(show_result_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(show_result_paneLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(show_result_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(show_result_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(wloss_reslt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mild_reslt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maintain_reslt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(show_result_paneLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel9))
                    .addGroup(show_result_paneLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel7)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        show_result_paneLayout.setVerticalGroup(
            show_result_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(show_result_paneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(show_result_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maintain_reslt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(show_result_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mild_reslt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(show_result_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wloss_reslt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(134, 134, 134))
        );

        jPanel6.add(show_result_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 450, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 650, 540));

        jPanel1.setBackground(new java.awt.Color(71, 120, 197));

        calci_panel.setBackground(new java.awt.Color(71, 120, 197));

        jLabel3.setFont(new java.awt.Font("Verdana Pro", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Age");

        text_age.setBackground(new java.awt.Color(71, 120, 197));
        text_age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_age.setForeground(new java.awt.Color(204, 204, 204));
        text_age.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_age.setBorder(null);
        text_age.setCaretColor(new java.awt.Color(204, 204, 204));
        text_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_ageActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana Pro", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Height(cm)");

        text_height.setBackground(new java.awt.Color(71, 120, 197));
        text_height.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_height.setForeground(new java.awt.Color(204, 204, 204));
        text_height.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_height.setBorder(null);
        text_height.setCaretColor(new java.awt.Color(204, 204, 204));
        text_height.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_heightActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana Pro", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Weight(kg)");

        text_weight.setBackground(new java.awt.Color(71, 120, 197));
        text_weight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_weight.setForeground(new java.awt.Color(204, 204, 204));
        text_weight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_weight.setBorder(null);
        text_weight.setCaretColor(new java.awt.Color(204, 204, 204));
        text_weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_weightActionPerformed(evt);
            }
        });

        activity_combobox.setBackground(new java.awt.Color(84, 127, 206));
        activity_combobox.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        activity_combobox.setForeground(new java.awt.Color(84, 127, 206));
        activity_combobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Basal Metabolic Rate (BMR)", "Secondary : little Exercise", "Light : Exercise 1-3 times/week", "Moderate : Exercise 4-5 times/week" }));
        activity_combobox.setBorder(new javax.swing.border.MatteBorder(null));
        activity_combobox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        activity_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activity_comboboxActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana Pro", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Activity");

        weight_loss_btn.setBackground(new java.awt.Color(71, 120, 197));
        weight_loss_btn.setFont(new java.awt.Font("Verdana Pro", 1, 12)); // NOI18N
        weight_loss_btn.setForeground(new java.awt.Color(23, 35, 51));
        weight_loss_btn.setText("Weight Loss");
        weight_loss_btn.setBorder(new javax.swing.border.MatteBorder(null));
        weight_loss_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weight_loss_btnActionPerformed(evt);
            }
        });

        weight_gain_btn.setBackground(new java.awt.Color(71, 120, 197));
        weight_gain_btn.setFont(new java.awt.Font("Verdana Pro", 1, 12)); // NOI18N
        weight_gain_btn.setForeground(new java.awt.Color(23, 35, 51));
        weight_gain_btn.setText("Weght Gain");
        weight_gain_btn.setBorder(new javax.swing.border.MatteBorder(null));
        weight_gain_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        weight_gain_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weight_gain_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout calci_panelLayout = new javax.swing.GroupLayout(calci_panel);
        calci_panel.setLayout(calci_panelLayout);
        calci_panelLayout.setHorizontalGroup(
            calci_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calci_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(calci_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calci_panelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calci_panelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calci_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator3)
                        .addComponent(text_height)
                        .addComponent(jSeparator2)
                        .addComponent(jSeparator4)
                        .addComponent(text_weight)
                        .addComponent(activity_combobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(text_age)))
                .addGap(204, 204, 204))
            .addGroup(calci_panelLayout.createSequentialGroup()
                .addGroup(calci_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calci_panelLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(calci_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(weight_gain_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(weight_loss_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addGroup(calci_panelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel4))
                    .addGroup(calci_panelLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        calci_panelLayout.setVerticalGroup(
            calci_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calci_panelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_age, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_height, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(activity_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(weight_loss_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(weight_gain_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(120, 168, 252));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCMS/images/user (2).png"))); // NOI18N
        profile_icon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(profile_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 70));

        profile_name.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        profile_name.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(profile_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 160, 30));

        logout_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCMS/images/icons8_Exit_25px.png"))); // NOI18N
        logout_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logout_btnMousePressed(evt);
            }
        });
        jPanel4.add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calci_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(calci_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 300, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1MousePressed
        // TODO add your handling code here:
        setColor(btn_1); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_3,btn_4}, new JPanel[]{ind_3, ind_4});
        calci_panel.setVisible(true);
    }//GEN-LAST:event_btn_1MousePressed

    private void btn_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_3MousePressed
        int guid = Integer.parseInt(uid.getText());
        
         setColor(btn_3); 
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btn_1,btn_4}, new JPanel[]{ind_1, ind_4});
        String pro_nm = profile_name.getText();
        String hm_uid = uid.getText();
        this.dispose();
        setgoal sg =new setgoal();
        sg.profile_name.setText(pro_nm);
        sg.uid.setText(hm_uid);
        try{
               Class.forName("com.mysql.jdbc.Driver");
               Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/dcmms","root","tiger");
               
               PreparedStatement pst = con.prepareStatement("select goalweight from goalweight where gid = '"+ guid +"' ");
//               pst.setString(1, gwuid);
               ResultSet rst = pst.executeQuery();
               if(rst.next())
               {
                   
                   sg.calgoal_label.setText(rst.getString(1) + " Calories");
//                   System.out.println(rst.getString(1));
                   
               }
           }    catch (Exception ex)
           {
               System.out.println(ex);
           }  
        sg.setSize(1070,590); 
        sg.setVisible(true);
        
        
    }//GEN-LAST:event_btn_3MousePressed

    private void btn_4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_4MousePressed
        // TODO add your handling code here:
          setColor(btn_4); 
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{btn_3,btn_1}, new JPanel[]{ind_3, ind_1});
        String pro_nm = profile_name.getText();
        String hm_uid = uid.getText();
        this.dispose();
        track sg =new track();
        sg.setSize(1070,590); 
        sg.setVisible(true);
        sg.profile_name.setText(pro_nm);
        sg.uid.setText(hm_uid);
    }//GEN-LAST:event_btn_4MousePressed

    int xx,xy;
    private void title_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title_panelMousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_title_panelMousePressed

    private void title_panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title_panelMouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_title_panelMouseDragged

    private void text_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_ageActionPerformed

    private void text_heightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_heightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_heightActionPerformed

    private void text_weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_weightActionPerformed

    private void activity_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activity_comboboxActionPerformed
     //  int  activity = (int) activity_combobox.getItemAt(activity_combobox.getSelectedIndex());
    }//GEN-LAST:event_activity_comboboxActionPerformed

    private void weight_loss_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weight_loss_btnActionPerformed
        show_result_pane.setVisible(true);
        int age = Integer.parseInt(text_age.getText());
        int height = Integer.parseInt(text_height.getText());        
        int weight = Integer.parseInt(text_weight.getText());
      int bmr ;
      int bmr_af;
      String bmr_r;
      //float result;
      bmr = (int) ((10 * weight) + ( 6.25 * height) - (5 * age) + 5 ) ;
     // System.out.println(bmr);
        if( activity_combobox.getSelectedIndex() == 0){
            jLabel13.setVisible(false);
            jLabel17.setVisible(false);
            jLabel7.setVisible(false);
            jLabel9.setVisible(false);
            mild_reslt.setVisible(false);
            wloss_reslt.setVisible(false);
            bmr_r = String.valueOf(bmr);
            maintain_reslt.setText(bmr_r+ "Calories / Day");
            
        }
        else if(activity_combobox.getSelectedIndex() == 1)
        {
            jLabel13.setVisible(true);
            jLabel17.setVisible(true);
            jLabel7.setVisible(true);
            jLabel9.setVisible(true);
            mild_reslt.setVisible(true);
            wloss_reslt.setVisible(true);
            bmr_af = (int) (bmr * 1.2) ;
            bmr_r = String.valueOf(bmr_af);
            maintain_reslt.setText(bmr_r + " Calories / Day");
            
            bmr_af = (int) (bmr * 1.05) ;
            bmr_r = String.valueOf(bmr_af);
            mild_reslt.setText(bmr_r + " Calories / Day");
            
            bmr_af = (int) (bmr * 0.89) ;
            bmr_r = String.valueOf(bmr_af);
            wloss_reslt.setText(bmr_r + " Calories / Day ");
        }
        else if(activity_combobox.getSelectedIndex() == 2)
        {
            jLabel13.setVisible(true);
            jLabel17.setVisible(true);
            jLabel7.setVisible(true);
            jLabel9.setVisible(true);
            mild_reslt.setVisible(true);
            wloss_reslt.setVisible(true);
            bmr_af = (int) (bmr * 1.375) ;
            bmr_r = String.valueOf(bmr_af);
            maintain_reslt.setText(bmr_r + " Calories / Day");
            
            bmr_af = (int) (bmr * 1.25) ;
            bmr_r = String.valueOf(bmr_af);
            mild_reslt.setText(bmr_r + " Calories / Day");
            
            bmr_af = (int) (bmr * 1.05) ;
            bmr_r = String.valueOf(bmr_af);
            wloss_reslt.setText(bmr_r + " Calories / Day");
        }
        else if(activity_combobox.getSelectedIndex() == 3)
        {
            jLabel13.setVisible(true);
            jLabel17.setVisible(true);
            jLabel7.setVisible(true);
            jLabel9.setVisible(true);
            mild_reslt.setVisible(true);
            wloss_reslt.setVisible(true);
            bmr_af = (int) (bmr * 1.5) ;
            bmr_r = String.valueOf(bmr_af);
            maintain_reslt.setText(bmr_r + " Calories / Day");
            
            bmr_af = (int) (bmr * 1.35) ;
            bmr_r = String.valueOf(bmr_af);
            mild_reslt.setText(bmr_r + " Calories / Day");
            
            bmr_af = (int) (bmr * 1.2) ;
            bmr_r = String.valueOf(bmr_af);
            wloss_reslt.setText(bmr_r + " Calories / Day");
        }
    }//GEN-LAST:event_weight_loss_btnActionPerformed

    private void weight_gain_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weight_gain_btnActionPerformed
       show_result_pane.setVisible(true);
        int age = Integer.parseInt(text_age.getText());
        int height = Integer.parseInt(text_height.getText());        
        int weight = Integer.parseInt(text_weight.getText());
      int bmr ;
      int bmr_af;
      String bmr_r;
      float result;
      bmr = (int) ((10 * weight) + ( 6.25 * height) - (5 * age) + 5 ) ;
     // System.out.println(bmr);
        if( activity_combobox.getSelectedIndex() == 0){
            jLabel13.setVisible(false);
            jLabel17.setVisible(false);
            jLabel7.setVisible(false);
            jLabel9.setVisible(false);
            mild_reslt.setVisible(false);
            wloss_reslt.setVisible(false);
            bmr_r = String.valueOf(bmr);
            maintain_reslt.setText(bmr_r + " Calories/ Day");
            
        }
        else if(activity_combobox.getSelectedIndex() == 1)
        {
            jLabel13.setVisible(true);
            jLabel17.setVisible(true);
            jLabel7.setVisible(true);
            jLabel9.setVisible(true);
            mild_reslt.setVisible(true);
            wloss_reslt.setVisible(true);
            bmr_af = (int) (bmr * 1.2) ;
            bmr_r = String.valueOf(bmr_af);
            maintain_reslt.setText(bmr_r + " Calories/ Day");
            
            bmr_af = (int) (bmr * 1.35) ;
            bmr_r = String.valueOf(bmr_af);
            jLabel13.setText("Mild weight gain");
            mild_reslt.setText(bmr_r + " Calories/ Day");
            
            bmr_af = (int) (bmr * 1.5) ;
            bmr_r = String.valueOf(bmr_af);
            jLabel17.setText("Weight gain");
            wloss_reslt.setText(bmr_r + " Calories/ Day");
        }
        else if(activity_combobox.getSelectedIndex() == 2)
        {
            jLabel13.setVisible(true);
            jLabel17.setVisible(true);
            jLabel7.setVisible(true);
            jLabel9.setVisible(true);
            mild_reslt.setVisible(true);
            wloss_reslt.setVisible(true);
            bmr_af = (int) (bmr * 1.2) ;
            bmr_r = String.valueOf(bmr_af);
            maintain_reslt.setText(bmr_r + " Calories/ Day");
            
            bmr_af = (int) (bmr * 1.525) ;
            bmr_r = String.valueOf(bmr_af);
            jLabel13.setText("Mild weight gain");
            mild_reslt.setText(bmr_r + " Calories/ Day");
            
            bmr_af = (int) (bmr * 1.68) ;
            bmr_r = String.valueOf(bmr_af);
            jLabel17.setText("Weight gain");
            wloss_reslt.setText(bmr_r + " Calories / Day");
        }
        else if(activity_combobox.getSelectedIndex() == 3)
        {
            jLabel13.setVisible(true);
            jLabel17.setVisible(true);
            jLabel7.setVisible(true);
            jLabel9.setVisible(true);
            mild_reslt.setVisible(true);
            wloss_reslt.setVisible(true);
            bmr_af = (int) (bmr * 1.2) ;
            bmr_r = String.valueOf(bmr_af);
            maintain_reslt.setText(bmr_r + " Calories / Day");
            
            bmr_af = (int) (bmr * 1.615) ;
            bmr_r = String.valueOf(bmr_af);
            jLabel13.setText("Mild weight gain");
            mild_reslt.setText(bmr_r + " Calories / Day");
            
            bmr_af = (int) (bmr * 1.765) ;
            bmr_r = String.valueOf(bmr_af);
            jLabel17.setText("Weight gain");
            wloss_reslt.setText(bmr_r + " Calories / Day");
        }
    }//GEN-LAST:event_weight_gain_btnActionPerformed

    private void logout_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMousePressed
       login lo= new login();
        lo.setSize(1070, 590); 
        lo.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_logout_btnMousePressed

    private void uidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }
   
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for (JPanel pane1 : pane) {
            pane1.setBackground(new Color(23,35,51));
        }
        for (JPanel indicator : indicators) {
            indicator.setOpaque(false);           
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox activity_combobox;
    private javax.swing.JPanel btn_1;
    private javax.swing.JPanel btn_3;
    private javax.swing.JPanel btn_4;
    private javax.swing.JPanel calci_panel;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel logout_btn;
    private javax.swing.JLabel maintain_reslt;
    private javax.swing.JLabel mild_reslt;
    private javax.swing.JLabel profile_icon;
    public javax.swing.JLabel profile_name;
    private javax.swing.JPanel show_result_pane;
    private javax.swing.JPanel side_pane;
    private javax.swing.JTextField text_age;
    private javax.swing.JTextField text_height;
    private javax.swing.JTextField text_weight;
    private javax.swing.JPanel title_panel;
    public javax.swing.JTextField uid;
    private javax.swing.JButton weight_gain_btn;
    private javax.swing.JButton weight_loss_btn;
    private javax.swing.JLabel wloss_reslt;
    // End of variables declaration//GEN-END:variables
}
