/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DCCMS;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public final class track extends javax.swing.JFrame {
 String foodp;
 String foodc;
String foodf;
 String fqty;
 String sfood;
 String foodcal;
 String foodn;
     /**
     * Creates new form Home
     */

 
    public track() {
        
    
        
        initComponents();
        
        setColor(btn_4); 
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{btn_5,btn_1,btn_3}, new JPanel[]{ind_5,ind_1, ind_3});
        uid.setVisible(false);
       
       
     
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        side_pane = new javax.swing.JPanel();
        btn_1 = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_3 = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_4 = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btn_5 = new javax.swing.JPanel();
        ind_5 = new javax.swing.JPanel();
        title_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        searchfood_panel = new javax.swing.JPanel();
        searchfood_text = new javax.swing.JTextField();
        searchf_btn = new javax.swing.JButton();
        foodqty_text = new javax.swing.JTextField();
        foodresult_text = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addf_btn = new javax.swing.JButton();
        calgoal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dcal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        profile_icon = new javax.swing.JLabel();
        profile_name = new javax.swing.JLabel();
        logout_btn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane.setBackground(new java.awt.Color(23, 35, 51));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_1.setBackground(new java.awt.Color(23, 35, 51));
        btn_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_1MousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Home");

        javax.swing.GroupLayout btn_1Layout = new javax.swing.GroupLayout(btn_1);
        btn_1.setLayout(btn_1Layout);
        btn_1Layout.setHorizontalGroup(
            btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_1Layout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(0, 66, Short.MAX_VALUE))
        );
        btn_1Layout.setVerticalGroup(
            btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_1Layout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 120, -1));

        btn_3.setBackground(new java.awt.Color(23, 35, 51));
        btn_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_3MousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Set Goal");

        javax.swing.GroupLayout btn_3Layout = new javax.swing.GroupLayout(btn_3);
        btn_3.setLayout(btn_3Layout);
        btn_3Layout.setHorizontalGroup(
            btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_3Layout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(0, 56, Short.MAX_VALUE))
        );
        btn_3Layout.setVerticalGroup(
            btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_3Layout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 120, -1));

        btn_4.setBackground(new java.awt.Color(23, 35, 51));
        btn_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_4MousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Track Calories");

        javax.swing.GroupLayout btn_4Layout = new javax.swing.GroupLayout(btn_4);
        btn_4.setLayout(btn_4Layout);
        btn_4Layout.setHorizontalGroup(
            btn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_4Layout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        btn_4Layout.setVerticalGroup(
            btn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_4Layout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 120, -1));

        btn_5.setBackground(new java.awt.Color(23, 35, 51));
        btn_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_5MouseReleased(evt);
            }
        });

        ind_5.setOpaque(false);
        ind_5.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_5Layout = new javax.swing.GroupLayout(ind_5);
        ind_5.setLayout(ind_5Layout);
        ind_5Layout.setHorizontalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_5Layout.setVerticalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btn_5Layout = new javax.swing.GroupLayout(btn_5);
        btn_5.setLayout(btn_5Layout);
        btn_5Layout.setHorizontalGroup(
            btn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_5Layout.createSequentialGroup()
                .addComponent(ind_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 117, Short.MAX_VALUE))
        );
        btn_5Layout.setVerticalGroup(
            btn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_5Layout.createSequentialGroup()
                .addComponent(ind_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        side_pane.add(btn_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 120, -1));

        getContentPane().add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 590));

        title_panel.setBackground(new java.awt.Color(71, 120, 197));
        title_panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                title_panelMouseDragged(evt);
            }
        });
        title_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                title_panelMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana Pro Cond Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(176, 221, 243));
        jLabel1.setText("Daily Calorie Calculator and Management System");

        uid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout title_panelLayout = new javax.swing.GroupLayout(title_panel);
        title_panel.setLayout(title_panelLayout);
        title_panelLayout.setHorizontalGroup(
            title_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, title_panelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(uid, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(177, 177, 177))
        );
        title_panelLayout.setVerticalGroup(
            title_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(title_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(title_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 950, 50));

        jPanel6.setBackground(new java.awt.Color(84, 127, 206));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchfood_panel.setBackground(new java.awt.Color(84, 127, 206));

        searchfood_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchfood_textActionPerformed(evt);
            }
        });

        searchf_btn.setBackground(new java.awt.Color(71, 120, 197));
        searchf_btn.setFont(new java.awt.Font("Verdana Pro", 1, 12)); // NOI18N
        searchf_btn.setForeground(new java.awt.Color(23, 35, 51));
        searchf_btn.setText("Search Food");
        searchf_btn.setBorder(new javax.swing.border.MatteBorder(null));
        searchf_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchf_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchfood_panelLayout = new javax.swing.GroupLayout(searchfood_panel);
        searchfood_panel.setLayout(searchfood_panelLayout);
        searchfood_panelLayout.setHorizontalGroup(
            searchfood_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchfood_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(searchfood_text, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(searchf_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addGap(99, 99, 99))
        );
        searchfood_panelLayout.setVerticalGroup(
            searchfood_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(searchfood_panelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(searchfood_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchfood_text, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchf_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.add(searchfood_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        foodqty_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodqty_textActionPerformed(evt);
            }
        });
        jPanel6.add(foodqty_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 85, 50, 40));

        foodresult_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodresult_textActionPerformed(evt);
            }
        });
        jPanel6.add(foodresult_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 85, 180, 40));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food Item", "Qty(g)", "Protein(g)", "Fat(g)", "Carbohydrates(g)", "Calories"
            }
        ));
        jTable1.setMinimumSize(new java.awt.Dimension(100, 100));
        jTable1.setPreferredSize(new java.awt.Dimension(400, 400));
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 590, 230));

        addf_btn.setBackground(new java.awt.Color(71, 120, 197));
        addf_btn.setFont(new java.awt.Font("Verdana Pro", 1, 12)); // NOI18N
        addf_btn.setForeground(new java.awt.Color(23, 35, 51));
        addf_btn.setText("Add Food");
        addf_btn.setBorder(new javax.swing.border.MatteBorder(null));
        addf_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addf_btnActionPerformed(evt);
            }
        });
        jPanel6.add(addf_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 88, 73, 33));

        calgoal.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        calgoal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(calgoal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 120, 30));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Your Consumed :");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 140, 30));

        dcal.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        dcal.setForeground(new java.awt.Color(255, 255, 255));
        dcal.setText("         0   /");
        jPanel6.add(dcal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 70, 30));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 650, 540));

        jPanel1.setBackground(new java.awt.Color(71, 120, 197));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(120, 168, 252));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCMS/images/user (2).png"))); // NOI18N
        profile_icon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(profile_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 70));

        profile_name.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        profile_name.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(profile_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 160, 30));

        logout_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCMS/images/icons8_Exit_25px.png"))); // NOI18N
        logout_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logout_btnMousePressed(evt);
            }
        });
        jPanel4.add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 299, 88));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 300, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1MousePressed
        // TODO add your handling code here:
        setColor(btn_1); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_5,btn_3,btn_4}, new JPanel[]{ind_5,ind_3, ind_4});
        String pro_nm = profile_name.getText();
        String hm_uid = uid.getText();
        this.dispose();
        Home sg =new Home();
        sg.setSize(1070,590); 
        sg.setVisible(true);
        sg.profile_name.setText(pro_nm);
        sg.uid.setText(hm_uid);
    }//GEN-LAST:event_btn_1MousePressed

    private void btn_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_3MousePressed
        // TODO add your handling code here:
         setColor(btn_3); 
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btn_5,btn_1,btn_4}, new JPanel[]{ind_5,ind_1, ind_4});
        String pro_nm = profile_name.getText();
        String hm_uid = uid.getText();
        this.dispose();
        setgoal sg =new setgoal();
        sg.setSize(1070,590); 
        sg.setVisible(true);
        sg.profile_name.setText(pro_nm);
        sg.uid.setText(hm_uid);
        
    }//GEN-LAST:event_btn_3MousePressed

    private void btn_4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_4MousePressed
        // TODO add your handling code here:
          setColor(btn_4); 
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{btn_5,btn_3,btn_1}, new JPanel[]{ind_5,ind_3, ind_1});
    }//GEN-LAST:event_btn_4MousePressed

    int xx,xy;
    private void title_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title_panelMousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_title_panelMousePressed

    private void title_panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title_panelMouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_title_panelMouseDragged

    private void btn_5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_5MousePressed
       
    }//GEN-LAST:event_btn_5MousePressed

    private void btn_5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_5MouseReleased
        setColor(btn_5); 
        ind_5.setOpaque(true);
        resetColor(new JPanel[]{btn_4,btn_3,btn_1}, new JPanel[]{ind_4,ind_3, ind_1});// TODO add your handling code here:
    }//GEN-LAST:event_btn_5MouseReleased

    private void logout_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMousePressed
       login lo= new login();
        lo.setSize(1070, 590); 
        lo.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_logout_btnMousePressed

    private void uidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uidActionPerformed

    private void searchfood_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchfood_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchfood_textActionPerformed

    private void foodqty_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodqty_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodqty_textActionPerformed

    private void foodresult_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodresult_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodresult_textActionPerformed

    private void searchf_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchf_btnActionPerformed
        
        sfood = searchfood_text.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/dcmms","root","tiger");  
            PreparedStatement pst = con.prepareStatement("select * from food where fname =? ");
            pst.setString(1, sfood);
            ResultSet rst = pst.executeQuery();
            if(rst.next())
            {
                foodresult_text.setText(rst.getString(2));
                foodqty_text.setText(rst.getString(7));  
               /*   foodp = rst.getString(3);
                foodc = rst.getString(4);
                foodf = rst.getString(5);
                foodcal = rst.getString(6);
                fqty = rst.getString(7);
                DefaultTableModel model = (DefaultTableModel) (jTable1.getModel());
                model.addRow(new Object[]{sfood,fqty, foodp, foodf, foodc, foodcal});   */
            }
            
             
    }
 catch (Exception ex)
{
System.out.println(ex);
}
    }//GEN-LAST:event_searchf_btnActionPerformed

    private void addf_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addf_btnActionPerformed
        showcal();
        int foodqty = Integer.parseInt(foodqty_text.getText());
        
       try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/dcmms","root","tiger");  
            PreparedStatement pst = con.prepareStatement("select * from food where fname =? ");
            pst.setString(1, sfood);
            ResultSet rst = pst.executeQuery();
            if(rst.next())
            {
                foodn = rst.getString("fname");
                foodp = rst.getString("fprotein");
                foodc = rst.getString("fcarbs");
                foodf = rst.getString("ffat");
                foodcal = rst.getString("calories");
                fqty = rst.getString("quantity");
                
                float p = Float.parseFloat(foodp);
                Float fp;
                fp = p * foodqty;
                
                float f = Float.parseFloat(foodf);
                Float ff;
                ff = f * foodqty;
                
                float c = Float.parseFloat(foodc);
                Float fc;
                fc = c * foodqty;
                
                float cal = Float.parseFloat(foodcal);
                Float fcal;
                fcal = cal * foodqty;
               
                Object item[] = {foodn,foodqty, fp, ff, fc, fcal};
                DefaultTableModel model = (DefaultTableModel) (jTable1.getModel());
                model.addRow(item);
                
               
                String calval = String.valueOf(model.getValueAt(0,5));
                String calval1 = String.valueOf(model.getValueAt(1,5));
                String calval2 = String.valueOf(model.getValueAt(2,5));
//                String calval3 = String.valueOf((String )model.getValueAt(3,5));
//                String calval4 = String.valueOf((String )model.getValueAt(4,5));
//                String calval5 =String.valueOf((String )model.getValueAt(5,5));
               
                float cv = Float.valueOf(calval);
                float cv1 = Float.valueOf(calval1);
                float cv2 = Float.valueOf(calval2);
//                float cv3 = Float.valueOf(calval3);
//                float cv4 = Float.valueOf(calval4);
//                float cv5 = Float.valueOf(calval5);

                
                float calvalt;
                calvalt = cv + cv1 + cv2 ;
                     //    + cv3 + cv4 + cv5  ;
                String cvt = Float.toString(calvalt);
                dcal.setText(cvt + " /");
            }
            
             
    }
 catch (Exception ex)
{
System.out.println(ex);
}
     
    }//GEN-LAST:event_addf_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(() -> {
            new track().setVisible(true);
        });
        
    }
   
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for (JPanel pane1 : pane) {
            pane1.setBackground(new Color(23,35,51));
        }
        for (JPanel indicator : indicators) {
            indicator.setOpaque(false);           
        }
        
    }
    public void showcal(){
         int guid = Integer.parseInt(uid.getText());
         try{
               Class.forName("com.mysql.jdbc.Driver");
               Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/dcmms","root","tiger");
               
               PreparedStatement pst = con.prepareStatement("select goalweight from goalweight where gid = '"+ guid +"' ");

               ResultSet rst = pst.executeQuery();
               if(rst.next())
               {
                   
                   calgoal.setText(rst.getString(1) + " Calories");

               }
           }    catch (Exception ex)
           {
               System.out.println(ex);
           }  
     
    
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addf_btn;
    private javax.swing.JPanel btn_1;
    private javax.swing.JPanel btn_3;
    private javax.swing.JPanel btn_4;
    private javax.swing.JPanel btn_5;
    public javax.swing.JLabel calgoal;
    public javax.swing.JLabel dcal;
    private javax.swing.JTextField foodqty_text;
    private javax.swing.JTextField foodresult_text;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JPanel ind_5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JLabel logout_btn;
    private javax.swing.JLabel profile_icon;
    public javax.swing.JLabel profile_name;
    public javax.swing.JButton searchf_btn;
    private javax.swing.JPanel searchfood_panel;
    private javax.swing.JTextField searchfood_text;
    private javax.swing.JPanel side_pane;
    private javax.swing.JPanel title_panel;
    public javax.swing.JTextField uid;
    // End of variables declaration//GEN-END:variables
}
